version: '1'
services:
  frontend:
    image: 'frontend'
    build:
      context: .
      dockerfile: dev.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/app/app
      - ./components:/app/components
      - ./config:/app/config
    environment:
      WATCHPACK_POLLING: true
      NODE_OPTIONS: --max-old-space-size=8192
      APP_URL: ${APP_URL}
      NODE_ENV: development
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      BACKEND_URL: ${BACKEND_URL}
