version: '2'

services:
  frontend:
    image: 'ccm-frontend'
    build:
      context: .
      dockerfile: Dockerfile.Production
    ports:
      - '3000:3000'
    networks:
      - codecommunitymusic-network

networks:
  codecommunitymusic-network:
