export const Interests = [
    "Reading",
    "Writing",
    "Gaming",
    "Music",
    "Movies",
    "TV Shows",
    "Anime",
    "Manga",
    "Webtoons",
    "Webnovels",
    "Coding",
    "Open Source",
    "Problem Solving",
    "Algorithms",
    "Data Structures",
    "Software Development",
    "Web Development",
    "Mobile Development",
    "Game Development",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Cybersecurity",
    "Blockchain",
    "Cloud Computing",
    "Internet of Things",
    "DevOps",
    "Agile Methodologies",
    "UI/UX Design",
    "Responsive Design",
    "Front-end Development",
    "Back-end Development",
    "Full-stack Development",
    "Serverless Architecture",
    "Version Control",
    "Continuous Integration/Continuous Deployment (CI/CD)",
    "Test-driven Development",
    "Tech Communities",
    "Meetups",
    "Conferences",
    "Hackathons",
    "Code Review",
    "Blogging",
    "Technical Writing",
    "Mentoring",
    "Learning New Technologies",
    "Experimenting with Frameworks/Libraries",
    "Automation",
    "Linux",
    "Command Line",
    "Productivity Tools",
    "Building Personal Projects",
    "Contributing to Open Source Projects",
    "Collaboration",
    "Learning New Programming Languages",
    "Podcasts",
    "Online Learning Platforms",
    "Video Tutorials",
    "Code Challenges",
    "Code Golf",
    "Building Developer Tools",
] as const;
