export const Types = [
    "Open Source",
    "Closed Source",
    "Web Application",
    "Mobile Application",
    "Desktop Application",
    "Game",
    "API",
    "Library",
    "Framework",
    "CLI",
    "Plugin",
    "Extension",
    "Bot",
    "Script",
    "Utility",
    "Tool",
    "Service",
    "Database",
    "Operating System",
    "Browser",
    "IDE",
    "Editor",
    "CMS",
    "eCommerce",
    "Social Media",
    "Blockchain",
    "Cybersecurity",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Cloud Computing",
    "DevOps",
    "Internet of Things",
    "Other",
] as const;



export const TechStacks = [
    "JavaScript",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "Java",
    "Spring Boot",
    "C#",
    ".NET",
    "Python",
    "Flask",
    "Django",
    "Ruby",
    "Rails",
    "SQL",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Git",
    "SVN",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "RESTful APIs",
    "GraphQL",
    "OAuth",
    "JSON",
    "XML"
] as const;