export const Skills = [
    "JavaScript",
    "HTML",
    "CSS",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Ruby on Rails",
    "PHP",
    "Laravel",
    "Java",
    "Spring Boot",
    "C#",
    ".NET",
    "Python",
    "Flask",
    "Django",
    "Ruby",
    "Rails",
    "SQL",
    "MongoDB",
    "MySQL",
    "PostgreSQL",
    "Git",
    "SVN",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Docker",
    "Kubernetes",
    "RESTful APIs",
    "GraphQL",
    "OAuth",
    "JSON",
    "XML",
    "Unit Testing",
    "Integration Testing",
    "Test-driven Development",
    "CI/CD",
    "Agile Methodologies",
    "UI/UX Design",
    "Responsive Web Design",
    "Cross-browser Compatibility",
    "Version Control",
    "Problem Solving",
    "Debugging",
    "Data Structures",
    "Algorithms",
    "Object-oriented Programming",
    "Functional Programming",
    "Software Development Lifecycle",
    "Web Development",
    "Mobile Development",
    "Game Development",
    "Artificial Intelligence",
    "Machine Learning",
    "Data Science",
    "Cybersecurity",
    "Blockchain",
    "Cloud Computing",
    "Internet of Things",
    "DevOps",
    "Shell Scripting",
    "Linux",
    "Command Line",
    "Productivity Tools",
    "Collaboration",
    "Technical Writing",
    "Documentation",
    "Mentoring",
    "Project Management",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Leadership",
    "Communication",
    "Teamwork",
] as const;
